---
title: Fab Lab Joinville
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contato@fablabjoinville.com.br
description: Um laboratório onde você pode fazer quase qualquer coisa.
baseurl: ''
url: http://www.fablabjoinville.com.br
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
